export const DATA = Object.freeze([
  {
    id: 0,
    title: "Black loafers",
    category: "shoes",
    tags: ["Black", "Casual", "Dark", "Demiseason", "Formal", "Leather"],
    image: "IMG_20230801_102327",
    active: "1",
  },
  {
    id: 1,
    title: "Loafers with sparkles",
    category: "shoes",
    tags: ["Casual", "Gray", "Light", "Summer"],
    image: "IMG_0930",
    active: "1",
  },
  {
    id: 2,
    title: "Sandals sport",
    category: "shoes",
    tags: [	"Gray", "Sport", "Summer"],
    image: "IMG_0929",
    active: "1",
  },
  {
    id: 3,
    title: "Blue asics shoes",
    category: "shoes",
    tags: [	"Blue", "Dark", "Sport", "Summer"],
    image: "IMG_0788",
    active: "1",
  },
  {
    id: 4,
    title: "White nike shoes",
    category: "shoes",
    tags: ["Casual", "Demiseason", "White", "Leather"],
    image: "IMG_0787",
    active: "1",
  },
  {
    id: 5,
    title: "Sport shoes nike black",
    category: "shoes",
    tags: ["Black", "Dark", "Sport", "Summer"],
    image: "IMG_0787",
    active: "1",
  },
  {
    id: 6,
    title: "Sandals ecco",
    category: "shoes",
    tags: [	"Casual", "Summer", "White", "Leather"],
    image: "IMG_0789",
    active: "1",
  },
  {
    id: 7,
    title: "Shoes black ecco",
    category: "shoes",
    tags: [	"Black", "Casual", "Demiseason", "Leather"],
    image: "IMG_0785",
    active: "1",
  },
  {
    id: 8,
    title: "Shoes adidas",
    category: "shoes",
    tags: [	"Demiseason", "Green", "Sport", "White", "Leather"],
    image: "IMG_0784",
    active: "1",
  },
  {
    id: 9,
    title: "Cross shoulder bag",
    category: "bags",
    tags: [	"Blue", "Casual", "Demiseason", "Small", "Summer"],
    image: "IMG_0777",
    active: "1",
  },
  {
    id: 10,
    title: "Banana bag",
    category: "bags",
    tags: ["Black", "Leather", "Small"],
    image: "IMG_0775",
    active: "1",
  },
  {
    id: 11,
    title: "Bag from Mexico",
    category: "bags",
    tags: [	"Blue", "Casual", "Light", "Summer"],
    image: "IMG_0781",
    active: "1",
  },
  {
    id: 12,
    title: "Shopper bag Vitebsk",
    category: "bags",
    tags: ["Shopper",	"Casual", "Summer", "White"],
    image: "IMG_0780",
    active: "1",
  },
  {
    id: 13,
    title: "Shopper bag with fish",
    category: "bags",
    tags: ["Shopper",	"Casual", "Summer", "White", "Small"],
    image: "IMG_0779",
    active: "1",
  },
  {
    id: 14,
    title: "Backpack white",
    category: "bags",
    tags: [	"Backpack", "Casual", "Demiseason", "Summer", "White", "Leather"],
    image: "IMG_0778",
    active: "1",
  },
  {
    id: 15,
    title: "Backpack gray",
    category: "bags",
    tags: [	"Backpack", "Big", "Casual", "Gray", "Sport"],
    image: "IMG_0782",
    active: "1",
  },
  {
    id: 16,
    title: "Shopper bag Dortmund",
    category: "bags",
    tags: ["Shopper",	"Casual", "Summer", "White", "Big"],
    image: "IMG_0783",
    active: "1",
  },
  {
    id: 17,
    title: "Black baguette bag",
    category: "bags",
    tags: ["Black", "Casual", "Dark", "Demiseason", "Leather", "Small", "Formal"],
    image: "IMG_0776",
    active: "1",
  },
  {
    id: 18,
    title: "Black backpack",
    category: "bags",
    tags: ["Black", "Dark", "Demiseason", "Leather", "Summer", "Winter"],
    image: "IMG_0774",
    active: "1",
  },
  {
    id: 19,
    title: "Linen shorts",
    category: "pants",
    tags: ["Blue", "Casual", "Dark", "Linen", "Shorts", "Summer"],
    image: "IMG_0923",
    active: "1",
  },
  {
    id: 20,
    title: "Casual shorts",
    category: "pants",
    tags: ["Blue", "Casual", "Shorts", "Summer"],
    image: "IMG_0921",
    active: "1",
  },
  {
    id: 21,
    title: "Cycling shorts",
    category: "pants",
    tags: [	"Black", "Dark", "Shorts", "Sport", "Summer"],
    image: "IMG_0797",
    active: "1",
  },
  {
    id: 22,
    title: "Jeans blue",
    category: "pants",
    tags: [	"Blue", "Casual", "Demiseason", "Jeans", "Summer"],
    image: "IMG_0763",
    active: "1",
  },
  {
    id: 23,
    title: "Sport shorts",
    category: "pants",
    tags: [	"Dark", "Green", "Sport", "Summer", "Shorts"],
    image: "IMG_0924",
    active: "1",
  },
  {
    id: 24,
    title: "Leather Skirt",
    category: "pants",
    tags: [	"Black", "Casual", "Dark", "Demiseason", "Leather", "Winter", "Skirt", "Formal"],
    image: "IMG_0764",
    active: "1",
  },
  {
    id: 25,
    title: "Jeans black",
    category: "pants",
    tags: [	"Black", "Casual", "Dark", "Demiseason", "Jeans", "Winter"],
    image: "IMG_0756",
    active: "1",
  },
  {
    id: 26,
    title: "Jeans lightblue",
    category: "pants",
    tags: [	"Casual", "Demiseason", "Jeans", "Blue", "Demiseason", "Winter"],
    image: "IMG_0757",
    active: "1",
  },
  {
    id: 27,
    title: "Linen shirt",
    category: "coats",
    tags: [	"Blue", "Casual", "Linen", "Summer", "Shirt"],
    image: "IMG_0922",
    active: "1",
  },
  {
    id: 28,
    title: "Shirt in blue strips",
    category: "coats",
    tags: ["Casual", "Blue", "White", "Shirt", "Summer"],
    image: "IMG_0916",
    active: "1",
  },
  {
    id: 29,
    title: "Shirt white future is female",
    category: "coats",
    tags: ["White", "Casual", "Demiseason", "Formal", "Shirt"],
    image: "IMG_0914",
    active: "1",
  },
  {
    id: 30,
    title: "Shirt white",
    category: "coats",
    tags: [	"Casual", "Summer", "White", "Shirt"],
    image: "IMG_0773",
    active: "1",
  },
  {
    id: 31,
    title: "T-shirt liverpool 2020",
    category: "coats",
    tags: [	"Red", "Sport", "Summer"],
    image: "IMG_0768",
    active: "1",
  },
  {
    id: 32,
    title: "T-shirt happiness",
    category: "coats",
    tags: [	"Summer", "Gray", "Casual"],
    image: "IMG_0765",
    active: "1",
  },
  {
    id: 33,
    title: "Cardigan warm",
    category: "coats",
    tags: [	"Blue", "Casual", "Demiseason", "Winter", "Warm"],
    image: "IMG_0759",
    active: "1",
  },
  {
    id: 34,
    title: "Sweater milk color",
    category: "coats",
    tags: ["White", "Warm", "Demiseason", "Winter"],
    image: "IMG_0758",
    active: "1",
  },
  {
    id: 35,
    title: "Sweatshirt warmer",
    category: "coats",
    tags: [	"Black", "Dark", "Casual", "Demiseason", "Warm", "Winter"],
    image: "IMG_0755",
    active: "1",
  },
  {
    id: 36,
    title: "Sweatshirt with stock",
    category: "coats",
    tags: [	"Black", "Dark", "Casual", "Demiseason"],
    image: "IMG_0754",
    active: "1",
  },
  {
    id: 37,
    title: "Black t-shirt",
    category: "coats",
    tags: ["Black",	"Casual", "Summer", "Dark", "Formal", "Demiseason"],
    image: "IMG_0753",
    active: "1",
  },
  {
    id: 38,
    title: "Shirt pink",
    category: "coats",
    tags: [	"Pink", "Casual", "Shirt", "Summer"],
    image: "IMG_0771",
    active: "1",
  },
  {
    id: 39,
    title: "T-shirt blue",
    category: "coats",
    tags: [	"Blue", "Summer", "Casual", "Demiseason", "Sport"],
    image: "IMG_0767",
    active: "1",
  },
  {
    id: 40,
    title: "T-shirt gray",
    category: "coats",
    tags: ["Gray",	"Casual", "Summer", "Sport", "Demiseason"],
    image: "IMG_0766",
    active: "1",
  },
  {
    id: 41,
    title: "Sport dress",
    category: "full",
    tags: [	"Green", "Sport", "Summer", "Dress"],
    image: "IMG_0927",
    active: "1",
  },
  {
    id: 42,
    title: "Dress violet",
    category: "full",
    tags: [	"Dress", "Long", "Summer"],
    image: "IMG_0926",
    active: "1",
  },
  {
    id: 43,
    title: "Shirt green",
    category: "full",
    tags: ["Shirt", "Casual", "Green", "Summer"],
    image: "IMG_0925",
    active: "1",
  },
  {
    id: 44,
    title: "Overalls summer",
    category: "full",
    tags: ["Black", "Casual", "Shorts", "Summer"],
    image: "IMG_0915",
    active: "1",
  },
  {
    id: 45,
    title: "Jacket pink",
    category: "full",
    tags: [	"Pink", "Demiseason", "Jacket", "Casual", "Summer"],
    image: "IMG_0912",
    active: "1",
  },
  {
    id: 46,
    title: "Jacket lightgray",
    category: "full",
    tags: [	"Gray", "Jacket", "Casual", "Summer"],
    image: "IMG_0911",
    active: "1",
  },
  {
    id: 47,
    title: "Dress linen green",
    category: "full",
    tags: [	"Dark", "Green", "Demiseason", "Summer", "Dress", "Linen"],
    image: "IMG_0752",
    active: "1",
  },
  {
    id: 48,
    title: "Dress Lightblue",
    category: "full",
    tags: [	"Blue", "Casual", "Summer", "Dress"],
    image: "IMG_0918",
    active: "1",
  },
  {
    id: 49,
    title: "Dress Black",
    category: "full",
    tags: [	"Dark", "Black", "Casual", "Formal", "Summer"],
    image: "IMG_0917",
    active: "1",
  },
  {
    id: 50,
    title: "Windbreaker in dots",
    category: "full",
    tags: ["Blue", "Casual", "Dark", "Jacket", "Outerwear", "Summer"],
    image: "IMG_0792",
    active: "1",
  },
  {
    id: 51,
    title: "Bomber blue",
    category: "full",
    tags: ["Blue", "Casual", "Jacket", "Summer", "Outerwear", "Demiseason"],
    image: "IMG_0793",
    active: "1",
  },
  {
    id: 52,
    title: "Jacket black",
    category: "full",
    tags: [	"Black", "Dark", "Jacket", "Outerwear", "Demiseason", "Warm", "Casual"],
    image: "IMG_0794",
    active: "1",
  },
  {
    id: 53,
    title: "Zara coat",
    category: "full",
    tags: [	"Black", "Dark", "Jacket", "Outerwear", "Demiseason", "Warm", "Casual", "Leather", "Winter"],
    image: "IMG_0795",
    active: "1",
  },
  {
    id: 54,
    title: "White jeans coat",
    category: "full",
    tags: [	"White", "Jacket", "Jeans", "Summer"],
    image: "IMG_0796",
    active: "1",
  },
  {
    id: 55,
    title: "Dress Green with feathers",
    category: "full",
    tags: [	"Green", "Party", "Dress"],
    image: "IMG_0919",
    active: "1",
  },
  {
    id: 56,
    title: "Black Party Dress",
    category: "full",
    tags: [	"Dark", "Party", "Dress", "Black"],
    image: "IMG_0920",
    active: "1",
  },
  {
    id: 57,
    title: "Baseball hat",
    category: "hats",
    tags: ["White", "Hat", "Sport", "Summer"],
    image: "IMG_0937",
    active: "1",
  },
  {
    id: 58,
    title: "White winter hat",
    category: "hats",
    tags: ["White", "Casual", "Warm", "Winter"],
    image: "IMG_0931",
    active: "1",
  },
  {
    id: 59,
    title: "Gray scarf",
    category: "hats",
    tags: [	"Gray", "Dark", "Scarf", "Casual", "Warm", "Winter", "Scarf"],
    image: "IMG_0932",
    active: "1",
  },
  {
    id: 60,
    title: "Brown scarf",
    category: "hats",
    tags: [	"Brown", "Casual", "Demiseason", "Scarf", "Winter"],
    image: "IMG_0933",
    active: "1",
  },
  {
    id: 61,
    title: "Black hat",
    category: "hats",
    tags: [	"Dark", "Black", "Casual", "Winter"],
    image: "IMG_0934",
    active: "1",
  },
  {
    id: 62,
    title: "Black semi hat",
    category: "hats",
    tags: [	"Dark", "Black", "Casual", "Demiseason"],
    image: "IMG_0935",
    active: "1",
  },
  {
    id: 63,
    title: "Cherry hat and scarf",
    category: "hats",
    tags: [	"Dark", "Red", "Winter", "Demiseason"],
    image: "IMG_0936",
    active: "1",
  },
  {
    id: 64,
    title: "Pink Sweater",
    category: "coats",
    tags: ["Pink", "Demiseason", "Casual"],
    image: "IMG_0760",
    active: "1",
  },
  {
    id: 65,
    title: "Gray turtleneck",
    category: "coats",
    tags: [	"Gray", "Casual", "Light", "Demiseason"],
    image: "IMG_0761",
    active: "1",
  },
  {
    id: 66,
    title: "Black top",
    category: "coats",
    tags: ["Black",	"Casual", "Demiseason", "Dark"],
    image: "IMG_0762",
    active: "1",
  },
  {
    id: 67,
    title: "Hoodie GAP",
    category: "coats",
    tags: ["Gray",	"Casual", "Summer", "Sport", "Demiseason"],
    image: "IMG_0769",
    active: "1",
  },
  {
    id: 68,
    title: "Turtleneck sweater",
    category: "coats",
    tags: [	"Brown", "Casual", "Demiseason", "Winter", "Warm"],
    image: "IMG_0790",
    active: "1",
  },
  {
    id: 69,
    title: "Striped brown sweater",
    category: "coats",
    tags: [	"Brown", "Warm", "Casual", "Dark", "Winter"],
    image: "IMG_0791",
    active: "1",
  },
]);
